
package br.usp.wikilibras.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ISignDictionaryWS", targetNamespace = "http://ws.wikilibras.usp.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISignDictionaryWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.usp.wikilibras.ws.Sign
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signByName", targetNamespace = "http://ws.wikilibras.usp.br/", className = "br.usp.wikilibras.ws.SignByName")
    @ResponseWrapper(localName = "signByNameResponse", targetNamespace = "http://ws.wikilibras.usp.br/", className = "br.usp.wikilibras.ws.SignByNameResponse")
    public Sign signByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.usp.wikilibras.ws.Sign>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nearSigns", targetNamespace = "http://ws.wikilibras.usp.br/", className = "br.usp.wikilibras.ws.NearSigns")
    @ResponseWrapper(localName = "nearSignsResponse", targetNamespace = "http://ws.wikilibras.usp.br/", className = "br.usp.wikilibras.ws.NearSignsResponse")
    public List<Sign> nearSigns(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.usp.wikilibras.ws.Sign
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "simpleTranslate", targetNamespace = "http://ws.wikilibras.usp.br/", className = "br.usp.wikilibras.ws.SimpleTranslate")
    @ResponseWrapper(localName = "simpleTranslateResponse", targetNamespace = "http://ws.wikilibras.usp.br/", className = "br.usp.wikilibras.ws.SimpleTranslateResponse")
    public Sign simpleTranslate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.usp.wikilibras.ws.Sign>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "translate", targetNamespace = "http://ws.wikilibras.usp.br/", className = "br.usp.wikilibras.ws.Translate")
    @ResponseWrapper(localName = "translateResponse", targetNamespace = "http://ws.wikilibras.usp.br/", className = "br.usp.wikilibras.ws.TranslateResponse")
    public List<Sign> translate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
