
package br.usp.wikilibras.ws;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SignDictionaryWSService", targetNamespace = "http://ws.wikilibras.usp.br/", wsdlLocation = "http://localhost:8081/wikilibras/ws/dictionary?wsdl")
public class SignDictionaryWSService
    extends Service
{

    private final static URL SIGNDICTIONARYWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.usp.wikilibras.ws.SignDictionaryWSService.class.getName());

    static {
    	
        // incluído manualmente
        File file = new File("conf/polilibras.conf");
        Properties properties = new Properties();
        try {
            properties.load(new FileInputStream(file));
        } catch (IOException e1) {
            e1.printStackTrace();
        }
        String wsdl = properties.getProperty("dictionary_wsdl"); 
        // incluído manualmente
    	
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.usp.wikilibras.ws.SignDictionaryWSService.class.getResource(".");
            url = new URL(baseUrl, wsdl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/wikilibras/ws/dictionary?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SIGNDICTIONARYWSSERVICE_WSDL_LOCATION = url;
    }

    public SignDictionaryWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SignDictionaryWSService() {
        super(SIGNDICTIONARYWSSERVICE_WSDL_LOCATION, new QName("http://ws.wikilibras.usp.br/", "SignDictionaryWSService"));
    }

    /**
     * 
     * @return
     *     returns ISignDictionaryWS
     */
    @WebEndpoint(name = "SignDictionaryWSPort")
    public ISignDictionaryWS getSignDictionaryWSPort() {
        return super.getPort(new QName("http://ws.wikilibras.usp.br/", "SignDictionaryWSPort"), ISignDictionaryWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISignDictionaryWS
     */
    @WebEndpoint(name = "SignDictionaryWSPort")
    public ISignDictionaryWS getSignDictionaryWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wikilibras.usp.br/", "SignDictionaryWSPort"), ISignDictionaryWS.class, features);
    }

}
